"""
Erdos-Straus Conjecture -- Session 7: Theorem 7 -- NQR Covering

SESSION 6 BREAKTHROUGH:
  QR Criterion: For x=x_lo+t with A_t prime, a solution exists iff
    the subgroup generated by {prime_factors(B_t) mod A_t} contains -B_t mod A_t.

  At t=1 (A=7): B_1 = p*(p+7)/4 = 2p^2 (mod 7) [always QR].
  -B_1 = NQR mod 7 always.
  => t=1 works iff B_1 has a QNR prime factor mod 7.
  => p = 3,5,6 (mod 7) => p itself is QNR. t=1 works.
  => p = 1,2,4 (mod 7) => need x_1=(p+7)/4 to have a QNR factor mod 7.

THIS SESSION: THEOREM 7 -- NQR-mod-7 Formula
  For p = NQR (mod 7), i.e., p = 3,5,6 (mod 7):
    Gateway divisor d = 2^k * p (where k is chosen so d = -B_1 mod 7):
      p = 3 (mod 7), i.e., p = 17 (mod 28): k=0, d=p.
      p = 6 (mod 7), i.e., p = 13 (mod 28): k=1, d=2p.
      p = 5 (mod 7), i.e., p = 5  (mod 28): k=2, d=4p.

  Closed form: 4/p = 1/x1 + 1/y + 1/z
    x1 = (p+7)/4
    y  = p*(p+7+4*2^k) / 28
    z  = p*(p+7)*(p+7+4*2^k) / (112*2^k)

  Unified table (where c_k = 4*2^k, so c=4,8,16 for k=0,1,2):
    p=17(mod 28) [r=3]: 4/p = 1/((p+7)/4) + 1/(p(p+11)/28) + 1/(p(p+7)(p+11)/112)
    p=13(mod 28) [r=6]: 4/p = 1/((p+7)/4) + 1/(p(p+15)/28) + 1/(p(p+7)(p+15)/224)
    p= 5(mod 28) [r=5]: 4/p = 1/((p+7)/4) + 1/(p(p+23)/28) + 1/(p(p+7)(p+23)/448)

ALGEBRAIC PROOF SKETCH:
  At x1 = (p+7)/4, A=7, B1=p*(p+7)/4 (always even since (p+7)/4 even for p=1 mod 8).
  4/p - 1/x1 = 7/B1. Need 1/y + 1/z = 7/B1.
  Substituting d = 2^k * p as gateway:
    y = (d + B1)/7 = (2^k*p + p*(p+7)/4)/7 = p*(4*2^k + p+7)/28.
    z = B1*y/d = (p*(p+7)/4) * (p*(p+7+4*2^k)/28) / (2^k*p)
      = p*(p+7)*(p+7+4*2^k) / (112*2^k).
  Integrality proofs:
    y: 28 | p*(p+7+4*2^k). Note p is coprime to 28. Need 28|p+7+4*2^k.
      p=17(mod 28): p+11 = p+7+4 = 28k+28 = 0(mod 28). CHECK k=0.
      p=13(mod 28): p+15 = p+7+8 = 28k+28 = 0(mod 28). CHECK k=1.
      p= 5(mod 28): p+23 = p+7+16= 28k+28 = 0(mod 28). CHECK k=2.
    z: 112*2^k | p*(p+7)*(p+7+4*2^k). p coprime to 112*2^k.
      8 | (p+7): p=1(mod 8) => p+7=0(mod 8). CHECK.
      (28/gcd) | (p+7+4*2^k): 28|(p+7+4*2^k) [shown above].
      But also need 2^k to appear: (p+7) is even (8|p+7), and
      8*(28/gcd) may or may not equal 112*2^k. Direct check:
        k=0: need 112|p*(p+7)*(p+11). 8|p+7, 14|p+11 (since 28|p+11). 8*14=112. CHECK.
        k=1: need 224|p*(p+7)*(p+15). 8|p+7, 28|p+15. 8*28=224. CHECK.
        k=2: need 448|p*(p+7)*(p+23). 8|p+7, 28|p+23. Also: 8|p+23 since 8|p+7 and
             (p+23)-(p+7)=16=2*8 => 8|p+23. So 16|p+7 or (8|p+7 and 8|p+23) =>
             16 divides (p+7)*(p+23)/(8) ... need 64*7|(p+7)*(p+23). Since 8|p+7 and
             8|p+23: (p+7)*(p+23) has 8*8=64 factor. 7|p+23 (28|p+23). 64*7=448. CHECK.

COVERAGE: ~50% of Case B primes (by Dirichlet density, NQR mod 7 has density 3/6).
  Combined with Theorems 1-5: covers ~97% of ALL primes.
  Remaining ~3%: Case B primes with p=QR mod 7 (p=1,2,4 mod 7).

GOAL THIS SESSION:
  1. Prove and verify Theorem 7 (NQR-mod-7 formulas).
  2. Study QR-mod-7 Case B: derive t=2 (A=11) analogues.
  3. Compute total provably-covered prime fraction.
  4. State the complete proof outline for all primes.

Date: Session 7, March 2026
"""

import math
import time
from collections import defaultdict
from pathlib import Path

RESULTS_DIR = Path(__file__).parent / "results"
RESULTS_DIR.mkdir(exist_ok=True)


def sieve_primes(limit):
    is_prime = bytearray([1]) * (limit + 1)
    is_prime[0] = is_prime[1] = 0
    for i in range(2, int(limit**0.5) + 1):
        if is_prime[i]:
            is_prime[i*i::i] = bytearray(len(is_prime[i*i::i]))
    return [i for i in range(2, limit + 1) if is_prime[i]]


def verify(n, x, y, z):
    return (y*z + x*z + x*y) * n == 4 * x * y * z


def is_case_b(p):
    if p % 24 != 1:
        return False
    x_lo = (p + 3) // 4
    n = x_lo
    d = 2
    while d * d <= n:
        if n % d == 0:
            if d % 3 == 2:
                return False
            while n % d == 0:
                n //= d
        d += 1
    return not (n > 1 and n % 3 == 2)


# ── Theorem 7 Formulas ──────────────────────────────────────────────────────────

def theorem7_formula(p):
    """
    THEOREM 7 (NQR-mod-7 Case B):
    For p = 1 (mod 24) Case B with p = NQR (mod 7):
      p = 3 (mod 7), i.e., p = 17 (mod 28): k=0
      p = 6 (mod 7), i.e., p = 13 (mod 28): k=1
      p = 5 (mod 7), i.e., p =  5 (mod 28): k=2
    Returns (x1, y, z) or None if p is not in this theorem's scope.
    """
    r = p % 7
    if r not in (3, 5, 6):
        return None  # QR mod 7, not handled here

    k = {3: 0, 6: 1, 5: 2}[r]
    c = 4 * (2 ** k)  # c = 4, 8, 16 for k=0,1,2

    # Check residue mod 28
    expected_mod28 = {3: 17, 6: 13, 5: 5}[r]
    assert p % 28 == expected_mod28, f"p={p} has p%7={r} but p%28={p%28}, expected {expected_mod28}"

    x1 = (p + 7) // 4
    assert (p + 7) % 4 == 0

    # y = p*(p+7+c)/28
    y_num = p * (p + 7 + c)
    assert y_num % 28 == 0, f"28 does not divide y_num={y_num} for p={p}, k={k}"
    y = y_num // 28

    # z = p*(p+7)*(p+7+c) / (112*2^k)
    z_denom = 112 * (2 ** k)
    z_num = p * (p + 7) * (p + 7 + c)
    assert z_num % z_denom == 0, f"z not integer for p={p}, k={k}: {z_num}/{z_denom}"
    z = z_num // z_denom

    return (x1, y, z)


# ── Theorem 7 Verification ──────────────────────────────────────────────────────

def verify_theorem7(prime_limit=2_000_000):
    """
    Verify Theorem 7 for ALL Case B primes p = NQR (mod 7) up to prime_limit.
    """
    print(f"\n{'='*60}")
    print(f"THEOREM 7 VERIFICATION (Case B, NQR mod 7, primes to {prime_limit:,})")
    print(f"{'='*60}")
    print(f"  Formulas:")
    print(f"    p=17(mod 28): 4/p = 1/((p+7)/4) + 1/(p(p+11)/28) + 1/(p(p+7)(p+11)/112)")
    print(f"    p=13(mod 28): 4/p = 1/((p+7)/4) + 1/(p(p+15)/28) + 1/(p(p+7)(p+15)/224)")
    print(f"    p= 5(mod 28): 4/p = 1/((p+7)/4) + 1/(p(p+23)/28) + 1/(p(p+7)(p+23)/448)")

    primes = sieve_primes(prime_limit)
    nqr7 = {3, 5, 6}

    by_class = {3: {'count': 0, 'fails': []},
                5: {'count': 0, 'fails': []},
                6: {'count': 0, 'fails': []}}
    t0 = time.time()

    for p in primes:
        if not is_case_b(p):
            continue
        r = p % 7
        if r not in nqr7:
            continue
        by_class[r]['count'] += 1
        result = theorem7_formula(p)
        if result is None:
            by_class[r]['fails'].append(p)
            continue
        x1, y, z = result
        if not verify(p, x1, y, z):
            by_class[r]['fails'].append(p)

    elapsed = time.time() - t0
    total = sum(v['count'] for v in by_class.values())
    total_fails = sum(len(v['fails']) for v in by_class.values())
    print(f"\n  Checked {total:,} primes in {elapsed:.1f}s")
    print(f"  Total failures: {total_fails}")

    for r in [3, 5, 6]:
        c = by_class[r]
        mod28 = {3: 17, 6: 13, 5: 5}[r]
        print(f"\n  p={r}(mod 7) [p={mod28}(mod 28)]: {c['count']:,} primes, "
              f"failures={c['fails'][:5]}")

    if total_fails == 0:
        print(f"\n  THEOREM 7 VERIFIED: All {total:,} Case B NQR-mod-7 primes "
              f"to {prime_limit:,} have closed-form solutions. PROVEN.")

    # Show examples
    print(f"\n  Examples:")
    examples = {3: [], 5: [], 6: []}
    for p in primes:
        if all(len(examples[r]) >= 3 for r in [3, 5, 6]):
            break
        if not is_case_b(p):
            continue
        r = p % 7
        if r in examples and len(examples[r]) < 3:
            result = theorem7_formula(p)
            if result:
                x1, y, z = result
                examples[r].append((p, x1, y, z))
    for r in [3, 5, 6]:
        for p, x1, y, z in examples[r]:
            print(f"    p={p:6d} (mod 28={p%28}): 4/{p} = 1/{x1} + 1/{y} + 1/{z}")

    return total, total_fails


# ── QR-mod-7 Analysis: t=2 Formula Attempt ─────────────────────────────────────

def derive_t2_formula():
    """
    For Case B primes with p = QR (mod 7) [p=1,2,4 mod 7]:
    t=1 fails when x_1=(p+7)/4 has all prime factors QR mod 7.

    Try t=2: A=11, x2=(p+11)/4, B2=p*(p+11)/4 (ODD since x2 odd).
    B2 = 3p^2 (mod 11) [always QR mod 11].
    -B2 = NQR mod 11. Works if B2 has a QNR factor mod 11.

    For p = QNR (mod 11) [p = 2,6,7,8,10 (mod 11)]:
      p itself is NQR mod 11. Use d = p as gateway for A=11.
      d = p = -B2 (mod 11)? B2 = 3p^2 (mod 11). -B2 = -3p^2 (mod 11).
      Need p = -3p^2 (mod 11) => 1 = -3p (mod 11) => p = -1/3 = -4 = 7 (mod 11).
      So d=p works only when p = 7 (mod 11), which is a NQR (7 in NQR11). Specific!

    Better approach: find gateway d for each p mod 11 class.
    B2 = p*(p+11)/4. -B2 mod 11 = -3p^2 mod 11.
    p mod 11 -> 3p^2 mod 11 -> -3p^2 mod 11 (target):
      p=1: 3*1=3, target=8 (NQR). QNRs={2,6,7,8,10}.
      p=2: 3*4=12=1, target=10.
      p=3: 3*9=27=5, target=6.
      p=4: 3*16=48=4, target=7.
      p=5: 3*25=75=9, target=2.
      p=6: 3*36=108=9, target=2.
      p=7: 3*49=147=4, target=7.
      p=8: 3*64=192=5, target=6.
      p=9: 3*81=243=1, target=10.
      p=10:3*100=300=3, target=8.

    For each target: we need d | B2^2 and d = target (mod 11).
    d = 2^a * p^b * (x2_factors)... complex.

    SIMPLIFICATION: For the case p = 7 (mod 11) (NQR, target=7=p mod 11):
      d = p works! p = 7 (mod 11) = target. y=(p+B2)/11=p*(1+x2)/11=p*(p+15)/(4*11)=p*(p+15)/44.
      Need 44 | p*(p+15). p coprime to 44. Need 44|p+15.
      p=7(mod 11): p+15 = p+11+4 = 11k+4+11 = 11(k+1)+4... not 0 mod 44 generically.
      p=1(mod 4) AND p=7(mod 11): by CRT p=7(mod 44) -- does p+15=22 work? 22/44 no.
        Actually p=7(mod 44): p+15=22. 44 | 22? No. This doesn't work cleanly.

    The t=2 case is harder because B2 is ODD (no free factor of 2).
    """
    print(f"\n{'='*60}")
    print(f"T=2 FORMULA ANALYSIS (A=11, QR-mod-7 Case B primes)")
    print(f"{'='*60}")

    print(f"  B2 = p*(p+11)/4. B2 = 3p^2 (mod 11) [QR]. -B2 = NQR mod 11.")
    print(f"  Target gateway d = -B2 mod 11 by p mod 11:")
    nqr11 = {2, 6, 7, 8, 10}
    targets = {}
    for pmod in range(1, 11):
        b2mod = (3 * pmod * pmod) % 11
        target = (11 - b2mod) % 11
        is_nqr = target in nqr11
        targets[pmod] = (b2mod, target)
        print(f"    p={pmod:2d}(mod 11): B2={b2mod}(mod 11), -B2={target}(mod 11), "
              f"NQR={is_nqr}")

    # For p=5(mod 11) or p=6(mod 11): target=2. d=2 divides B2? B2 is ODD. d=2 doesn't divide B2^2.
    # Wait: B2 is ODD (x2=(p+11)/4 is ODD for p=1(mod 8)). So 2 does NOT divide B2.
    # d must divide B2^2. If d=2 and 2|B2^2 requires 2|B2, which fails for odd B2.
    # So d=2 can't work for t=2.
    # Need d=odd and d|-B2 (mod 11). The gateway must come from an ODD prime factor of B2.

    print(f"\n  B2 is ALWAYS ODD (x2=(p+11)/4 is odd since p+11=p+3+8=even+8=8(mod 16) "
          f"for p=1(mod 8), so (p+11)/4=2*(something odd), i.e., x2 is even... wait")
    # Actually: p=1(mod 8), p+11=p+11. p+11 mod 8: p=1(mod 8) -> p+11=12=4(mod 8) -> (p+11)/4=3(mod 2)=odd.
    # Wait: 12/4=3 (odd). So x2=(p+11)/4 is ODD. B2=p*x2=odd*odd=ODD. Confirmed.
    print(f"  Confirmation: p=1(mod 8), p+11=12(mod 8)=4(mod 8), (p+11)/4=3(mod 2)=ODD. B2=ODD.")
    print(f"  => Gateway d must be ODD for t=2.")

    # For t=2, the gateway must be an ODD prime factor of B2 = p*(p+11)/4.
    # Prime factors: p itself and prime factors of (p+11)/4.
    # For p=p(mod 11), B2 = 3p^2 (mod 11). Target = -3p^2 (mod 11).
    # If p = target (mod 11), i.e., p+3p^2 = 0 (mod 11) => p(1+3p)=0(mod 11) => 3p=-1 => p=-1/3=7(mod 11).
    # So d=p works when p=7(mod 11). But need p|B2^2 (which is trivially true since p|B2).
    # And y=(d+B2)/11 = (p+p*x2)/11 = p*(1+x2)/11. Need 11|p*(1+x2)=p*(1+(p+11)/4)=p*(p+15)/4.
    # Since p coprime to 11: 11|p+15? No: p=7(mod 11) -> p+15=22=0(mod 11). YES!
    # And 4|p+15? p=1(mod 4) -> p+15=16=0(mod 4). YES!
    # y = p*(p+15)/44. Integer for p=7(mod 11) and p=1(mod 4).
    # p=7(mod 11) and p=1(mod 4): by CRT, p=7(mod 44).
    print(f"\n  CASE: p=7(mod 11) [NQR], p=1(mod 4). d=p at t=2:")
    print(f"    p+15 = 0(mod 11) (since p=7(mod 11)) and 0(mod 4) (since p=1(mod 4)).")
    print(f"    => 44 | p+15. y = p*(p+15)/44 is an integer!")
    # z = B2*y/p = x2*y = (p+11)/4 * p*(p+15)/44 = p*(p+11)*(p+15)/176.
    # 176 = 16*11 = 4*44. Need 176 | p*(p+11)*(p+15).
    # p coprime to 176. 4|p+11: p=1(mod 4)->p+11=12=0(mod 4) YES! 44|p+15 (shown). 4*44=176. CHECK.
    print(f"    z = p*(p+11)*(p+15)/176. 4|p+11 (p=1 mod 4) and 44|p+15. 4*44=176. PROVEN.")
    print(f"\n  THEOREM 7e (p=7 mod 11, Case B QR-mod-7):")
    print(f"    4/p = 1/((p+11)/4) + 1/(p*(p+15)/44) + 1/(p*(p+11)*(p+15)/176)")

    # For p=NQR mod 11 and p != 7 mod 11 (other NQR classes: 2,6,8,10):
    # Target -B2 mod 11: p=2->10, p=6->2, p=8->6, p=10->8.
    # None of these equal p mod 11 (2!=10, 6!=2, 8!=6, 10!=8).
    # So d=p doesn't work for these; need different gateway.
    # For p=2(mod 11): target=10. Need d=odd divisor of B2^2 = 10(mod 11).
    #   x2=(p+11)/4 has factors. x2 mod 11: x2=(p+11)/4=p/4(mod 11) [since 11/4=0].
    #   4^{-1} mod 11 = 3. x2 = 3p (mod 11). For p=2(mod 11): x2=6(mod 11) [NQR].
    #   So x2 has a factor = NQR mod 11 (since x2 itself = 6 mod 11).
    #   Product p*x2 = 2*6=12=1(mod 11) [QR]. But we need a factor = 10 mod 11.
    #   Powers of 6: 6,36=3,18=7,42=9,54=10! 6^5 = 10 (mod 11). So factor 6^5 = 10(mod 11) works!
    #   But 6^5 = 7776. We need 7776 | B2^2. B2^2 = (p*x2)^2. If x2 has factor q=6(mod 11),
    #   then q^5 | x2^2 only if q^5 | x2^2, i.e., q^3 | x2 (since q^2 | x2^2 always).
    #   In general this requires specific structure of x2.

    print(f"\n  Other NQR-mod-11 classes: more complex gateway needed (product of factors).")
    print(f"  These are handled by the empirical scan within bounded y-dist.")


# ── Complete Coverage Analysis ──────────────────────────────────────────────────

def coverage_analysis(prime_limit=1_000_000):
    """
    Compute the total fraction of ALL primes now covered by proven theorems.
    """
    print(f"\n{'='*60}")
    print(f"COMPLETE COVERAGE ANALYSIS (all primes to {prime_limit:,})")
    print(f"{'='*60}")

    primes = sieve_primes(prime_limit)
    total = len(primes)

    counts = {
        'p2': 0,
        'thm1': 0,   # p=3(mod 4) -- Theorem 1
        'thm2': 0,   # p=5(mod 8) -- Theorem 2
        'thm4': 0,   # p=17(mod 24) -- Theorem 4
        'thm5': 0,   # p=1(mod 24) Case A -- Theorem 5
        'thm7': 0,   # p=1(mod 24) Case B, NQR mod 7 -- Theorem 7
        'open': 0,   # p=1(mod 24) Case B, QR mod 7 -- OPEN
    }

    nqr7 = {3, 5, 6}

    for p in primes:
        if p == 2:
            counts['p2'] += 1
        elif p % 4 == 3:
            counts['thm1'] += 1
        elif p % 8 == 5:
            counts['thm2'] += 1
        elif p % 24 == 17:
            counts['thm4'] += 1
        elif p % 24 == 1:
            x_lo = (p + 3) // 4
            # Check Case A vs B
            n = x_lo
            d = 2
            is_b = True
            while d * d <= n:
                if n % d == 0:
                    if d % 3 == 2:
                        is_b = False
                        break
                    while n % d == 0:
                        n //= d
                d += 1
            if n > 1 and n % 3 == 2:
                is_b = False

            if not is_b:
                counts['thm5'] += 1  # Case A
            else:
                r = p % 7
                if r in nqr7:
                    counts['thm7'] += 1  # Case B, NQR mod 7
                else:
                    counts['open'] += 1  # Case B, QR mod 7

    proven = (counts['p2'] + counts['thm1'] + counts['thm2'] +
              counts['thm4'] + counts['thm5'] + counts['thm7'])

    print(f"\n  {'Category':<38} {'Count':>8}  {'%':>6}  {'Status'}")
    print(f"  {'-'*72}")
    print(f"  {'p=2 (trivial)':<38} {counts['p2']:>8,}  {100*counts['p2']/total:>5.2f}%  PROVEN")
    print(f"  {'p=3(mod 4) [Thm 1]':<38} {counts['thm1']:>8,}  {100*counts['thm1']/total:>5.2f}%  PROVEN (closed form)")
    print(f"  {'p=5(mod 8) [Thm 2]':<38} {counts['thm2']:>8,}  {100*counts['thm2']/total:>5.2f}%  PROVEN (closed form)")
    print(f"  {'p=17(mod 24) [Thm 4]':<38} {counts['thm4']:>8,}  {100*counts['thm4']/total:>5.2f}%  PROVEN (closed form)")
    print(f"  {'p=1(mod 24) Case A [Thm 5]':<38} {counts['thm5']:>8,}  {100*counts['thm5']/total:>5.2f}%  PROVEN (q-gateway)")
    print(f"  {'p=1(mod 24) Case B NQR7 [Thm 7]':<38} {counts['thm7']:>8,}  {100*counts['thm7']/total:>5.2f}%  PROVEN (NQR formula)")
    print(f"  {'-'*72}")
    print(f"  {'PROVEN TOTAL':<38} {proven:>8,}  {100*proven/total:>5.2f}%")
    print(f"  {'OPEN: p=1(mod 24) Case B QR7':<38} {counts['open']:>8,}  {100*counts['open']/total:>5.2f}%  empirically 0 failures")
    print(f"  {'-'*72}")
    print(f"  {'ALL PRIMES':<38} {total:>8,}  100.00%")
    print(f"\n  OPEN fraction: {100*counts['open']/total:.3f}% of all primes to {prime_limit:,}")

    return counts, proven, total


# ── Theorem 7 Proof Statement ───────────────────────────────────────────────────

def print_theorem7_proof():
    print(f"\n{'='*60}")
    print(f"THEOREM 7 -- COMPLETE STATEMENT AND PROOF")
    print(f"{'='*60}")
    print("""
  THEOREM 7 (NQR-mod-7 Formula for Case B Primes):
  Let p be a prime with p = 1 (mod 24) [i.e., p = 1 mod 8 and p = 1 mod 3]
  such that x_lo = (p+3)/4 has all prime factors = 1 (mod 3) [Case B].
  Suppose p = NQR (mod 7), i.e., p = 3, 5, or 6 (mod 7).

  Define k by: p=3(mod 7) => k=0; p=6(mod 7) => k=1; p=5(mod 7) => k=2.
  Let c = 4*2^k (so c = 4, 8, 16 for k=0,1,2).
  Let x1 = (p+7)/4, y = p*(p+7+c)/28, z = p*(p+7)*(p+7+c)/(112*2^k).

  CLAIM: x1, y, z are positive integers and 4/p = 1/x1 + 1/y + 1/z.

  PROOF OF INTEGRALITY:
  (a) x1 = (p+7)/4: integer since p=1(mod 4).
  (b) y = p*(p+7+c)/28: 28 | p*(p+7+c). Since gcd(p,28)=1:
      Need 28 | p+7+c.
      k=0, c=4: p+11. p=17(mod 28): p+11=28=0(mod 28). OK.
      k=1, c=8: p+15. p=13(mod 28): p+15=28=0(mod 28). OK.
      k=2, c=16: p+23. p= 5(mod 28): p+23=28=0(mod 28). OK.
  (c) z = p*(p+7)*(p+7+c)/(112*2^k):
      Since gcd(p, 112*2^k)=1 (p prime > 7, p odd):
      Need (112*2^k) | (p+7)*(p+7+c).
      Since p=1(mod 8): 8|p+7.
      Since 28|p+7+c (shown in (b)): 28|p+7+c.
      For k=0: 8*14 = 112. [14|p+11 since 28|p+11]. CHECK.
      For k=1: 8*28 = 224. CHECK.
      For k=2: 8|p+7 and 8|p+23 [since (p+23)-(p+7)=16]. So 64|(p+7)*(p+23).
               28|p+23. 64*7 = 448 = 112*4. CHECK.

  PROOF OF CORRECTNESS (4/p = 1/x1 + 1/y + 1/z):
  1/x1 = 4/(p+7). 4/p - 4/(p+7) = 4(p+7-p)/(p(p+7)) = 28/(p(p+7)).
  Need 1/y + 1/z = 28/(p(p+7)) = 28/(p*(p+7)).

  Substituting y and z:
  1/y + 1/z = (p*(p+7+c)/28)^{-1} + (p*(p+7)*(p+7+c)/(112*2^k))^{-1}
            = 28/(p*(p+7+c)) + (112*2^k)/(p*(p+7)*(p+7+c))
            = [28*(p+7) + 112*2^k] / [p*(p+7)*(p+7+c)]
            = 28*[(p+7) + 4*2^k] / [p*(p+7)*(p+7+c)]
            = 28*(p+7+c) / [p*(p+7)*(p+7+c)]   [since c=4*2^k]
            = 28 / [p*(p+7)].   QED.

  SCOPE: Covers all Case B primes p=NQR(mod 7).
  By Dirichlet's theorem: NQR residues mod 7 are {3,5,6}, density 3/6 = 1/2.
  Among Case B primes (density ~6% of all primes), Theorem 7 covers ~3%.
  Combined with Theorems 1,2,4,5: provably covers ~97% of all primes.
  REMAINING: ~3% of all primes (Case B, p=QR mod 7) -- empirically zero failures.
""")


# ── Entry point ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("ERDOS-STRAUS -- SESSION 7: THEOREM 7 PROOF")
    print("=" * 60)
    print()
    print("Goal: Prove Theorem 7 (NQR-mod-7 formulas) for Case B primes.")
    print("This covers ~50% of Case B, bringing total proven coverage to ~97%.")
    print()

    # Print the proof
    print_theorem7_proof()

    # Verify Theorem 7 for all Case B NQR-mod-7 primes to 2M
    total_checked, total_fails = verify_theorem7(prime_limit=2_000_000)

    # Analyze t=2 formula
    derive_t2_formula()

    # Compute full coverage
    counts, proven, total = coverage_analysis(prime_limit=1_000_000)

    print(f"\n{'='*60}")
    print(f"SESSION 7 SUMMARY")
    print(f"{'='*60}")
    print()
    print(f"  THEOREM 7 PROVEN AND VERIFIED:")
    print(f"    {total_checked:,} Case B NQR-mod-7 primes to 2M.")
    print(f"    Failures: {total_fails}. ZERO.")
    print()
    print(f"  PROOF COMPLETE for Theorem 7 (algebraic + computational).")
    print()
    print(f"  FULL COVERAGE (primes to 1M):")
    print(f"    Proven: {100*proven/total:.3f}% of all primes.")
    print(f"    Open:   {100*counts['open']/total:.3f}% -- Case B, QR mod 7.")
    print()
    print(f"  OPEN FRACTION STRUCTURE:")
    print(f"    p=1(mod 24) Case B QR-mod-7: ~{100*counts['open']/total:.2f}% of primes.")
    print(f"    These require t>=2 (A=11 or higher).")
    print(f"    Empirically: zero failures to 2M primes (Session 5).")
    print(f"    QNR criterion met at t<=7 for all p<=300k (Session 6).")
    print()
    print(f"  REMAINING GAP:")
    print(f"    Prove: for ALL Case B QR-mod-7 primes, some t<=K satisfies")
    print(f"    the QNR criterion. This is the last open piece.")
    print(f"    A density argument (Linnik-type) shows this holds for all but")
    print(f"    a set of density 0, but the EFFECTIVE bound on K is unproven.")
    print()
    print(f"  Session 8 target: Prove the QNR criterion holds at t<=K_abs for")
    print(f"  ALL Case B primes via a Linnik-type prime density bound.")
    print()
    print("SESSION 7 COMPLETE.")
